FROM gayatri589/open-jdk

# Set the working directory inside the container
WORKDIR /app
     
# Copy the application JAR file  
COPY . /app   

# Start the application 
CMD ["java", "-jar", "/app/hospital-console.jar"]
