name: Build Appointment service image

on: 
  push:
    paths:
      - hospital-management/appointment-service/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Perform google formatter check
        run: |
          cd hospital-management/api-gateway
          mvn com.spotify.fmt:fmt-maven-plugin:check

      - name: Remove target directory
        run: |
          cd hospital-management/appointment-service
          rm -rf target

      - name: GitLeaks Scan
        run: |
          cd hospital-management/appointment-service
          docker pull prathameshkulkarni47/gitleaks
          docker run -v "$(pwd):/scan" prathameshkulkarni47/gitleaks

      - name: OWASP Scan
        if: false
        run: |
          cd hospital-management/appointment-service
          mvn org.owasp:dependency-check-maven:check

      - name: Build Docker Image
        run: 
          docker build -t ${{ secrets.DOCKER_REGISTRY_USER }}/appointment-service:latest -f dockerfile .
        working-directory: hospital-management/appointment-service

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Push Docker Image
        run: 
          docker push ${{secrets.DOCKER_REGISTRY_USER}}/appointment-service:latest

      - name: License finder
        run: |
          cd hospital-management/appointment-service
          docker pull prathameshkulkarni47/license-finder
          docker run -v "$(pwd):/scan" prathameshkulkarni47/license-finder
        continue-on-error: true
