name: Build Hospital Console project

on:
  push:
    paths:
      - hospital-management/**
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Perform google formatter check
        run: |
          cd hospital-management/hospital-console-project
          mvn com.spotify.fmt:fmt-maven-plugin:check

      - name: GitLeaks Scan
        uses: zricethezav/gitleaks-action@v1.3.0
        with:
          args: --path=cd hospital-management/hospital-console-project

      - name: OWASP Scan
        if: false
        run: |
          cd hospital-management/hospital-console-project
          mvn org.owasp:dependency-check-maven:check

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
