name: Base Image for Open jdk

on: 
  push:
    paths:
      - dev-sec-opps/base-images/**

jobs:
  build-open-jdk-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build open-jdk image
        run: docker build -t ${{ secrets.DOCKER_REGISTRY_USER }}/open-jdk:latest -f dev-sec-opps/base-images/openjdk.dockerfile .

      - name: Log in to Github Docker Registry
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }} 
          

      - name: Push open-jdk image
        run: docker push ${{ secrets.DOCKER_REGISTRY_USER }}/open-jdk:latest


      

  
